/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package phasmoghosttest;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 *
 * @author belpg
 */
public class GhostTest extends javax.swing.JFrame {

    /**
     * Creates new form GhostTest
     */
    public GhostTest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listEv1 = new javax.swing.JList<>();
        lblGhost = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listEv2 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        listEv3 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Evidencia");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Ghost:");

        listEv1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Emf", "Uv", "Spirit Box", "Orb", "Escrita", "D.O.T.S", "Temperatura" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listEv1);

        lblGhost.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblGhost.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("discover the ghost with evidences");

        jButton1.setText("Ghost Type");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        listEv2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Emf", "Uv", "Spirit Box", "Orb", "Escrita", "D.O.T.S", "Temperatura", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listEv2);

        listEv3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Emf", "Uv", "Spirit Box", "Orb", "Escrita", "D.O.T.S", "Temperatura", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(listEv3);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Evidencia");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Evidencia");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jScrollPane1))
                                        .addGap(38, 38, 38)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jScrollPane2))
                                        .addGap(38, 38, 38)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jScrollPane3)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblGhost, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2))
                .addGap(40, 40, 40)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblGhost, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Input (Evidences)
        String evi1, evi2, evi3;
        evi1 = listEv1.getSelectedValue();
        evi2 = listEv2.getSelectedValue();
        evi3 = listEv3.getSelectedValue();

        //Array evidence
        ArrayList<String> evi = new ArrayList(Arrays.asList(evi1, evi2, evi3));
        evi.toString();

        //Ghosts and Evidences
        ArrayList<String> spirit = new ArrayList(Arrays.asList("Emf", "Escrita", "Spirit Box"));
        ArrayList<String> wraith = new ArrayList(Arrays.asList("Emf", "Spirit Box", "D.O.T.S"));
        ArrayList<String> phantom = new ArrayList(Arrays.asList("Uv", "Spirit Box", "D.O.T.S"));
        ArrayList<String> polter = new ArrayList(Arrays.asList("Escrita", "Spirit Box", "Uv"));
        ArrayList<String> banshee = new ArrayList(Arrays.asList("Uv", "Orb", "D.O.T.S"));
        ArrayList<String> jinn = new ArrayList(Arrays.asList("Emf", "Temperatura", "Uv"));
        ArrayList<String> mare = new ArrayList(Arrays.asList("Escrita", "Spirit Box", "Orb"));
        ArrayList<String> revenant = new ArrayList(Arrays.asList("Escrita", "Temperatura", "Orb"));
        ArrayList<String> shade = new ArrayList(Arrays.asList("Emf", "Escrita", "Temperatura"));
        ArrayList<String> demon = new ArrayList(Arrays.asList("Uv", "Escrita", "Temperatura"));
        ArrayList<String> yurei = new ArrayList(Arrays.asList("D.O.T.S", "Orb", "Temperatura"));
        ArrayList<String> oni = new ArrayList(Arrays.asList("Emf", "D.O.T.S", "Temperatura"));
        ArrayList<String> yokai = new ArrayList(Arrays.asList("Orb", "Spirit Box", "D.O.T.S"));
        ArrayList<String> hantu = new ArrayList(Arrays.asList("Uv", "Temperatura", "Orb"));
        ArrayList<String> goryo = new ArrayList(Arrays.asList("Emf", "Uv", "D.O.T.S"));
        ArrayList<String> myling = new ArrayList(Arrays.asList("Emf", "Temperatura", "Orb"));
        ArrayList<String> onryo = new ArrayList(Arrays.asList("Orb", "Spirit Box", "Temperatura"));
        ArrayList<String> thetwins = new ArrayList(Arrays.asList("Emf", "Spirit Box", "Temperatura"));
        ArrayList<String> raiju = new ArrayList(Arrays.asList("Emf", "Orb", "D.O.T.S"));
        ArrayList<String> obake = new ArrayList(Arrays.asList("Emf", "Orb", "Uv"));
        ArrayList<String> mimic = new ArrayList(Arrays.asList("Spirit Box", "Temperatura", "Uv"));
        ArrayList<String> moroi = new ArrayList(Arrays.asList("Temperatura", "Spirit Box", "Escrita"));
        ArrayList<String> thaye = new ArrayList(Arrays.asList("Orb", "Escrita", "D.O.T.S"));
        ArrayList<String> deogen = new ArrayList(Arrays.asList("Escrita", "Spirit Box", "D.O.T.S"));

        //GhostType has values ​​of ghosts Arrays
        List<ArrayList<String>> ghostType = Arrays.asList(spirit, wraith, phantom, polter, banshee,
            jinn, mare,revenant, shade, demon, yurei, oni, yokai, hantu, goryo, myling, onryo, thetwins,
            raiju, obake, mimic, moroi, thaye, deogen);

        //GhostName have name of ghosts
        List<String> ghostName = Arrays.asList("Spirit", "Wraith", "Phantom", "Poltergeist", "Banshee", "Jinn",
            "Mare", "Revenant", "Shade", "Demon", "Yurei", "Oni", "Yokai", "Hantu", "Goryo", "Myling", "Onryo", "TheTwins",
            "Raiju", "Obake", "Mimic", "Moroi", "Thaye", "Deogen");

        //Test to see if there is repeat evidences
        if(evi1 == evi2 || evi1 == evi3 || evi2 == evi3){
            lblGhost.setText("Error");
        } else{ //Compare whether Evi is equal to Ghosts through size
            for(int i = 0; i < ghostType.size(); i++){
                ArrayList<String> currentghost = ghostType.get(i);
                if(evi.containsAll(currentghost) && currentghost.containsAll(evi)){ //Compare whethrer the values match
                    lblGhost.setText((String) ghostName.get(i));
                    break;
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GhostTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GhostTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GhostTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GhostTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GhostTest().setVisible(true);
            }
        });
    }    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblGhost;
    private javax.swing.JList<String> listEv1;
    private javax.swing.JList<String> listEv2;
    private javax.swing.JList<String> listEv3;
    // End of variables declaration//GEN-END:variables
}
